name: Update

on:
  workflow_dispatch:
  schedule:
  - cron: "*/60 * * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install psl publicsuffix whois
      - run: git config --local user.name "GitHub Action"
      - run: git config --local user.email "action@github.com"
      - run: ./update.sh | tee /tmp/commit-message
      - run: if git commit -a -F /tmp/commit-message; then git push; fi
